# Configuracao do handler Lambda do Quarkus
quarkus.lambda.handler=AdminManagementFunction

# Lambda deployments precisam usar legacy-jar
quarkus.package.jar.type=legacy-jar

dynamodb.admin.table.name=${ADMIN_TABLE_NAME}

